// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcGzBdfKpQ-yYGwd8GOmnmIlp9iSORbFw',
    appId: '1:228354961703:web:f1020b1bf6e1d94e28f902',
    messagingSenderId: '228354961703',
    projectId: 'projeto-mamae-20aef',
    authDomain: 'projeto-mamae-20aef.firebaseapp.com',
    storageBucket: 'projeto-mamae-20aef.appspot.com',
    measurementId: 'G-QTC2NJ92GB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdrmQoaZvtFDNJwkJTDO4LGDnrH_FbyUc',
    appId: '1:228354961703:android:34d0f1e1eb4faad328f902',
    messagingSenderId: '228354961703',
    projectId: 'projeto-mamae-20aef',
    storageBucket: 'projeto-mamae-20aef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0E4xHv4qo9dURdO-2CG4E6-J_dpJiarE',
    appId: '1:228354961703:ios:2467f04227b8ce7a28f902',
    messagingSenderId: '228354961703',
    projectId: 'projeto-mamae-20aef',
    storageBucket: 'projeto-mamae-20aef.appspot.com',
    iosClientId: '228354961703-qv54vji06q2lkc6gjv88hvepvgksfp93.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
