// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcGzBdfKpQ-yYGwd8GOmnmIlp9iSORbFw',
    appId: '1:228354961703:web:49da3a592d07ac3f28f902',
    messagingSenderId: '228354961703',
    projectId: 'projeto-mamae-20aef',
    authDomain: 'projeto-mamae-20aef.firebaseapp.com',
    storageBucket: 'projeto-mamae-20aef.appspot.com',
    measurementId: 'G-RMW38CL3G2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdrmQoaZvtFDNJwkJTDO4LGDnrH_FbyUc',
    appId: '1:228354961703:android:5c6a4f0a7aca63c128f902',
    messagingSenderId: '228354961703',
    projectId: 'projeto-mamae-20aef',
    storageBucket: 'projeto-mamae-20aef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0E4xHv4qo9dURdO-2CG4E6-J_dpJiarE',
    appId: '1:228354961703:ios:d3e475730823c2c328f902',
    messagingSenderId: '228354961703',
    projectId: 'projeto-mamae-20aef',
    storageBucket: 'projeto-mamae-20aef.appspot.com',
    iosClientId: '228354961703-b6vt5112vfv14aoghj1tocrni9fggqos.apps.googleusercontent.com',
    iosBundleId: 'com.example.tailsMommy',
  );
}
